name: continuous-integration

on:
    push:
        branches:
            - master
    pull_request:

permissions:
    contents: read
    packages: write
    actions: read

jobs:
    main:
        
        name: Nx Cloud - Main Job
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - uses: nrwl/nx-set-shas@v3
              with:
                  main-branch-name: 'master'
            - uses: bahmutov/npm-install@v2

            - run: yarn nx format:check
            - run: yarn nx affected -t lint --parallel=3
            - run: yarn nx affected -t build --parallel=3

    agents:
        name: Nx Cloud - Agents
        uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.13.0
        with:
            number-of-agents: 3
