name: continuous-integration

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    main:
        name: Nx Cloud - Main Job
        runs-on: ubuntu-latest
        steps:
            - uses: nrwl/nx-set-shas@v3
            - uses: bahmutov/npm-install@v1

            - run: yarn nx format:check
            - run: yarn nx affected -t lint --parallel=3
            - run: yarn nx affected -t build --parallel=3

    agents:
        name: Nx Cloud - Agents
        uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.13.0
        with:
            number-of-agents: 3
